#Hamoye Energy Consumption Data Test

In [1]:
# Load the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

In [2]:
uploaded = files.upload()
import io

Saving energydata_complete.csv to energydata_complete.csv

In [3]:
df = pd.read_csv(io.BytesIO(uploaded['energydata_complete.csv']))

# About this file
1. Date time year-month-day hour:minute:second
2. Appliances, energy use in Wh
3. lights, energy use of light fixtures in the house in Wh
4. T1, Temperature in kitchen area, in Celsius
5. RH_1, Humidity in kitchen area, in %
6. T2, Temperature in living room area, in Celsius
7. RH_2, Humidity in living room area, in %
8. T3, Temperature in laundry room area
9. RH_3, Humidity in laundry room area, in %
10. T4, Temperature in office room, in Celsius
11. RH_4, Humidity in office room, in %
12. T5, Temperature in bathroom, in Celsius
13. RH_5, Humidity in bathroom, in %
14. T6, Temperature outside the building (north side), in Celsius
15. RH_6, Humidity outside the building (north side), in %
16. T7, Temperature in ironing room , in Celsius
17. 7RH_7, Humidity in ironing room, in %
18. T8, Temperature in teenager room 2, in Celsius
19. RH_8, Humidity in teenager room 2, in %
20. T9, Temperature in parents room, in Celsius
21. RH_9, Humidity in parents room, in %
22. To, Temperature outside (from Chievres weather station), in Celsius
23. Pressure (from Chievres weather station), in mm Hg
24. RH_out, Humidity outside (from Chievres weather station), in %
25. Wind speed (from Chievres weather station), in m/s
26. Visibility (from Chievres weather station), in km
27. Tdewpoint (from Chievres weather station), Â°C
28. rv1, Random variable 1, nondimensional
29. rv2, Random variable 2, nondimensional

Where indicated, hourly data (then interpolated) from the nearest airport weather station (Chievres Airport, Belgium) was downloaded from a public data set from Reliable Prognosis, rp5.ru. Permission was obtained from Reliable Prognosis for the distribution of the 4.5 months of weather data.

#EDA and Missing Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [5]:
missing_data = pd.DataFrame({'Count':df.isna().sum(),'Percentage':df.isna().sum()/len(df)*100})
missing_data

             Count  Percentage
date             0         0.0
Appliances       0         0.0
lights           0         0.0
T1               0         0.0
RH_1             0         0.0
T2               0         0.0
RH_2             0         0.0
T3               0         0.0
RH_3             0         0.0
T4               0         0.0
RH_4             0         0.0
T5               0         0.0
RH_5             0         0.0
T6               0         0.0
RH_6             0         0.0
T7               0         0.0
RH_7             0         0.0
T8               0         0.0
RH_8             0         0.0
T9               0         0.0
RH_9             0         0.0
T_out            0         0.0
Press_mm_hg      0         0.0
RH_out           0         0.0
Windspeed        0         0.0
Visibility       0         0.0
Tdewpoint        0         0.0
rv1              0         0.0
rv2              0         0.0

In [6]:
  df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

12. From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two d.p.?

In [7]:
# 12 Linear Regression Model of t2(Living Room Area) vs t6(Temprature Outside) in Degree Celsius

# Load the necessary libraries
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# t2  is the feature and t6 is the target
# Extract the features and target variable from the normalized dataset

features_df_t = df.drop(columns=['date','Appliances','lights', 'T1', 'RH_1', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
                                           'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
                                           'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
                                           'Tdewpoint', 'rv1', 'rv2'])
target_t = df['T6']

scaler = MinMaxScaler()
normalised_df_t = pd.DataFrame(scaler.fit_transform(features_df_t), columns=features_df_t.columns)



# Split the data into training and testing sets
x_train_t2, x_test_t2, y_train_t6, y_test_t6 = train_test_split(features_df_t, target_t, test_size=0.3, random_state=42)

# Initialize and fit a Linear Regression Model
linear_model = LinearRegression()
linear_model.fit(x_train_t2, y_train_t6)

# Make predictions on the test set
predicted_values = linear_model.predict(x_test_t2)

# Calculate the R-squared score
r2_score_value = r2_score(y_test_t6, predicted_values)
rounded_r2_score = round(r2_score_value, 2)

# Print the R-squared score rounded to two decimal places
print("R^2 Score: ", rounded_r2_score)

R^2 Score:  0.64

13. Normalize the dataset using the MinMaxScaler after removing the following columns: [“date”, “lights”]. The target variable is “Appliances”. Use a 70-30 train-test set split with a random state of 42 (for reproducibility). Run a multiple linear regression using the training set and evaluate your model on the test set. Answer the following questions:

What is the Mean Absolute Error (in two decimal places)?

In [8]:
# 2 Multiple Linear Regression of All features vs Application Energy Consumption

# Load the necessary libraries
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error


# Extract the features and target variable from the normalized dataset
scaler = MinMaxScaler()
normalised_df_app = df.drop(columns=['date','lights'])
normalised_df_app = pd.DataFrame(scaler.fit_transform(normalised_df_app), columns=normalised_df_app.columns)

target_app = normalised_df_app['Appliances']
features_df_app = normalised_df_app.drop(columns=['Appliances'], axis = 1)

# Split the data into training and testing sets
x_train_app, x_test_app, y_train_app, y_test_app = train_test_split(features_df_app, target_app, test_size=0.3, random_state=42)

# Initialize and fit a Linear Regression model
linear_model = LinearRegression()
linear_model.fit(x_train_app, y_train_app)

# Make predictions on the test set
predicted_values_app = linear_model.predict(x_test_app)

# Calculate the R-squared score
r2_score_value_app = r2_score(y_test_app, predicted_values_app)
rounded_r2_score_app = round(r2_score_value_app, 2)

# Calculate performance metrics
linear_regression_mae = mean_absolute_error(y_test_app, predicted_values_app)

# Print the R-squared score rounded to two decimal places
# print("R^2 Score: ", rounded_r2_score_app)
# print('\n')



print('MAE:', round(linear_regression_mae, 2))

MAE: 0.05

14. What is the Residual Sum of Squares (in two decimal places)?

In [9]:
# Residual Sum of Squares for (RSS) Appliances MUltivarte Linear Regression Model

rss = np.sum(np.square(y_test_app - predicted_values_app))
print('RSS:', round (rss, 2))

RSS: 45.35

15. What is the Root Mean Squared Error (in three decimal places)

In [11]:
# Root Mean Squared Error for Appliances MUltivarte Linear Regression Model
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test_app, predicted_values_app)
rmse = round(np.sqrt(rmse), 3)
print('RMSE:', rmse)

RMSE: 0.088

16. What is the Coefficient of Determination (in two decimal places)?

In [24]:
# R^2 Score for Appliances MUltivarte Linear Regression Model

from sklearn.metrics import r2_score
# Calculate the R-squared score
r2_score_value_app = r2_score(y_test_app, predicted_values_app)
rounded_r2_score_app = round(r2_score_value_app, 2)

# Print the R-squared score rounded to two decimal places
print("R^2 Score: ", rounded_r2_score_app)

R^2 Score:  0.15

17. Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [13]:
# Download Packages
from sklearn.linear_model import LinearRegression, Lasso, Ridge

# Initialize Models
linear_model = LinearRegression()
lasso_regression_model = Lasso(alpha=0.001)
ridge_regression_model = Ridge(alpha=0.4)

# Fit Models
linear_model.fit(x_train_app, y_train_app)
lasso_regression_model.fit(x_train_app, y_train_app)
ridge_regression_model.fit(x_train_app, y_train_app)

# Model, Features df and Column Names
def weights(model, features, col_name):
    # Retrieve feature weights (coefficients) from the model and sort them in ascending order
    if hasattr(model, 'coef_'):  # Check if the model has 'coef_' attribute
        weights_df = pd.Series(model.coef_, features.columns).sort_values()        
        # print('Lenght other Models:', len(weights_df))
        # print('Shape Other Models:', weights_df.shape)

    else:
        weights_df = pd.Series([0] * len(features.columns), features.columns).sort_values()  # Handle models without coefficients        
        # print('Linear Reg Len:', len(weights_df))        
        # print('Shape Lin_Reg:', weights_df.shape)

    # Assign Column names to the DataFrame
    weights_df = pd.DataFrame(weights_df).reset_index()
    weights_df.columns = ['Features', col_name]  # Assign correct column name

    # Round the values in the specified column to three decimal places
    weights_df[col_name] = weights_df[col_name].round(3)

    # Return the DataFrame with feature names and their corresponding weights
    return weights_df

linear_model_weights_df = weights(linear_model, x_train_app, 'Linear_Model_Weight')
ridge_weights_df = weights(ridge_regression_model, x_train_app, 'Ridge_Weight')
lasso_weights_df = weights(lasso_regression_model, x_train_app, 'Lasso_Weight')

final_weights_df = pd.merge(linear_model_weights_df, ridge_weights_df, on='Features', how = 'inner')
final_weights_df = pd.merge(final_weights_df, lasso_weights_df, on='Features', how = 'inner')
final_weights_df

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_Weight
0          RH_2               -0.457        -0.411        -0.000
1         T_out               -0.322        -0.262         0.000
2            T2               -0.236        -0.201         0.000
3            T9               -0.190        -0.189        -0.000
4          RH_8               -0.158        -0.157        -0.000
5        RH_out               -0.078        -0.055        -0.050
6          RH_7               -0.045        -0.046        -0.000
7          RH_9               -0.040        -0.041        -0.000
8            T5               -0.016        -0.020        -0.000
9            T1               -0.003        -0.018         0.000
10          rv1                0.001         0.001        -0.000
11          rv2                0.001         0.001        -0.000
12  Press_mm_hg                0.007         0.007        -0.000
13           T7                0.010         0.010        -0.000
14   Visibility                0.012         0.012         0.000
15         RH_5                0.016         0.016         0.000
16         RH_4                0.026         0.025         0.000
17           T4                0.029         0.027        -0.000
18    Windspeed                0.029         0.030         0.003
19         RH_6                0.038         0.036        -0.000
20         RH_3                0.096         0.095         0.000
21           T8                0.102         0.101         0.000
22    Tdewpoint                0.118         0.083         0.000
23           T6                0.236         0.217         0.000
24           T3                0.291         0.288         0.000
25         RH_1                0.554         0.520         0.018

In [14]:
min_value = final_weights_df.loc[:, 'Linear_Model_Weight'].min()
max_value = final_weights_df.loc[:, 'Linear_Model_Weight'].max()

print('Min Val:', min_value)
print('Max Val:', max_value)

Min Val: -0.457
Max Val: 0.554

In [15]:
# Retrieve the rows with the minimum and maximum values
min_rows = final_weights_df[final_weights_df['Linear_Model_Weight'] == min_value]
max_rows = final_weights_df[final_weights_df['Linear_Model_Weight'] == max_value]


print('Min Val:', min_rows)
print('Max Val:', max_rows)

Min Val:   Features  Linear_Model_Weight  Ridge_Weight  Lasso_Weight
0     RH_2               -0.457        -0.411          -0.0
Max Val:    Features  Linear_Model_Weight  Ridge_Weight  Lasso_Weight
25     RH_1                0.554          0.52         0.018

In [16]:
# Concatenate the rows into a single DataFrame
result_df = pd.concat([min_rows, max_rows])

print("Result DataFrame:")
print(result_df)

Result DataFrame:
   Features  Linear_Model_Weight  Ridge_Weight  Lasso_Weight
0      RH_2               -0.457        -0.411        -0.000
25     RH_1                0.554         0.520         0.018

18. Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

In [26]:
# Ridge Regression
# Initialize the regression models
ridge_regression = Ridge(alpha=0.4)

# Fit the models on the training data
ridge_regression.fit(x_train_app, y_train_app)

# Make predictions on the test data
ridge_preds = ridge_regression.predict(x_test_app)

# Calculate performance metrics
ridge_rmse = mean_squared_error(y_test_app, ridge_preds, squared=False)

# Print the performance metrics
print("Ridge Regression RMSE:", round(ridge_rmse, 3))

Ridge Regression RMSE: 0.088

19. Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [18]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

# Initialize Models
linear_model = LinearRegression()
lasso_regression_model = Lasso(alpha=0.001)
ridge_regression_model = Ridge(alpha=0.4)

# Fit Models
linear_model.fit(x_train_app, y_train_app)
lasso_regression_model.fit(x_train_app, y_train_app)
ridge_regression_model.fit(x_train_app, y_train_app)

# Model, Features df and Column Names
def weights(model, features, col_name):
    # Retrieve feature weights (coefficients) from the model and sort them in ascending order
    if hasattr(model, 'coef_'):  # Check if the model has 'coef_' attribute
        weights_df = pd.Series(model.coef_, features.columns).sort_values()        
        # print('Lenght other Models:', len(weights_df))
        # print('Shape Other Models:', weights_df.shape)

    else:
        weights_df = pd.Series([0] * len(features.columns), features.columns).sort_values()  # Handle models without coefficients        
        # print('Linear Reg Len:', len(weights_df))        
        # print('Shape Lin_Reg:', weights_df.shape)

    # Assign Column names to the DataFrame
    weights_df = pd.DataFrame(weights_df).reset_index()
    weights_df.columns = ['Features', col_name]  # Assign correct column name

    # Round the values in the specified column to three decimal places
    weights_df[col_name] = weights_df[col_name].round(3)

    # Return the DataFrame with feature names and their corresponding weights
    return weights_df

linear_model_weights_df = weights(linear_model, x_train_app, 'Linear_Model_Weight')
ridge_weights_df = weights(ridge_regression_model, x_train_app, 'Ridge_Weight')
lasso_weights_df = weights(lasso_regression_model, x_train_app, 'Lasso_Weight')

In [19]:
lasso_weights_df

       Features  Lasso_Weight
0        RH_out        -0.050
1          RH_8        -0.000
2            T1         0.000
3     Tdewpoint         0.000
4    Visibility         0.000
5   Press_mm_hg        -0.000
6         T_out         0.000
7          RH_9        -0.000
8            T9        -0.000
9            T8         0.000
10         RH_7        -0.000
11          rv1        -0.000
12           T7        -0.000
13           T6         0.000
14         RH_5         0.000
15           T5        -0.000
16         RH_4         0.000
17           T4        -0.000
18         RH_3         0.000
19           T3         0.000
20         RH_2        -0.000
21           T2         0.000
22         RH_6        -0.000
23          rv2        -0.000
24    Windspeed         0.003
25         RH_1         0.018

In [28]:
# Convert to Boolean for counting

non_zero_vals = lasso_weights_df["Lasso_Weight"].astype(bool).sum(axis=0)

print("Non Zero values:", non_zero_vals)

Non Zero values: 3

20. What is the new RMSE with the lasso regression? (Answer should be in three (3) decimal places)

In [21]:
 # Initialize the regression models
lasso_regression = Lasso(alpha=0.001)

# Fit the models on the training dat
lasso_regression.fit(x_train_app, y_train_app)
   
# Make predictions on the test data
lasso_preds = lasso_regression.predict(x_test_app)
    
# Calculate performance metrics
lasso_rmse = mean_squared_error(y_test_app, lasso_preds, squared=False)    
print('Lasso RMSE:', round(lasso_rmse, 3))

Lasso RMSE: 0.094